version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./frontend/node_modules:/app/frontend/node_modules
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
    command: gunicorn -b 0.0.0.0:5000 backend.app:app
