version: '3.8'

volumes:
  frontend_build: {}

services:
  frontend_dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - frontend_build:/app/frontend/build
    ports:
      - "3000:3000"
    networks:
      - my_network
    container_name: game_server_frontend_dev
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8001
    profiles:
      - dev

  frontend_prod:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - frontend_build:/app/frontend/build
      - /home/kasper/projects/valheim/logs:/app/valheim/logs
    ports:
      - "3000:3000"
    networks:
      - my_network
    container_name: game_server_frontend_prod
    environment:
      - REACT_APP_SERVER_URL=https://gamme-server.ru
    profiles:
      - prod

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
      - frontend_build:/app/frontend/build
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=production
    networks:
      my_network:
        aliases:
          - fastapi-app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 4
    container_name: game_server_backend
    profiles:
      - prod

  backend_dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
      - frontend_build:/app/frontend/build
      - ./valheim/logs:/app/valheim/logs
    ports:
      - "8001:8000"
    environment:
      - FASTAPI_ENV=development
    networks:
       - my_network
    command: uvicorn app:app --host 0.0.0.0 --reload
    container_name: game_server_backend_dev
    profiles:
      - dev

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - my_network
    container_name: game_server_nginx
    profiles:
      - prod

networks:
  my_network:
