version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./frontend/node_modules:/app/frontend/node_modules
      - ./frontend/build:/app/frontend/build
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5001
